# CHATBOT INTENTS
GREETING = 'GREETING'
NEW_MEETING = 'NEW_MEETING'
LIST_MEETING = 'LIST_MEETING'
BOOKING_RESTAURANT = 'BOOKING_RESTAURANT'
ASK_FOR_A_TAXI = 'ASK_FOR_A_TAXI' 
LIST_TAXIS = 'LIST_TAXIS' 
SAY_GOODBYE = "SAY_GOODBYE"

# CHATBOT STATES
CHECKING_STATE = 'CHECKING_STATE'
STATE_ASSIGNED = "STATE_ASSIGNED"

# NUMERIC CONSTANTS
MIN_SIMILARITY = 0.95
THRESHOLD = 0.6